apiVersion: newrelic.com/v1beta2
kind: Instrumentation
metadata:
  name: newrelic-instrumentation
  namespace: newrelic
spec: # <--- O 'spec' começa aqui
  
  # === CORREÇÃO FINAL AQUI ===
  # O nome correto do campo é "namespaceLabelSelector"
  namespaceLabelSelector:
    matchLabels:
      newrelic-monitoring: "true"
  
  # A configuração do agente (que já estava correta)
  agent:
    language: python
    image: newrelic/newrelic-python-init:latest
    env:
      - name: NEW_RELIC_APP_NAME
        value: "azure-vote-front"
      - name: NEW_RELIC_LOG
        value: "stdout"
      - name: NEW_RELIC_LOG_LEVEL
        value: "info"
      - name: NEW_RELIC_DISTRIBUTED_TRACING_ENABLED
        value: "true"